### ISSUE TITLE
Error "DataTable" has already been declared

### ISSUE THREAD

**Issue by fadiljaelani** [DataTables/Dist-DataTables-Buttons-Bootstrap5#1]
The symbol "DataTable" has already been declared

    node_modules/datatables.net-buttons-bs5/js/buttons.bootstrap5.mjs:8:7:
      8 │ import DataTable from 'datatables.net-buttons';
        ╵        ~~~~~~~~~

  The symbol "DataTable" was originally declared here:

    node_modules/datatables.net-buttons-bs5/js/buttons.bootstrap5.mjs:7:7:
      7 │ import DataTable from 'datatables.net-bs5';
        ╵        ~~~~~~~~~
        
        
I use Laravel 9 and vite, this is my package.json

"datatables.net-bs5": "^1.13.0",
"datatables.net-buttons-bs5": "^2.3.0",
"datatables.net-select-bs5": "^1.4.0",

![image](https://user-images.githubusercontent.com/66046419/200346385-3ccf3cd1-96c7-4398-88d1-231b9d94c476.png)

can you help me?

**Comment by AllanJard** [comment]
Gah! Thank you. I'm on the case.

**Comment by fadiljaelani** [comment]
> Gah! Thank you. I'm on the case.

OK, I'm waiting. or is there an error in my code?

**Comment by AllanJard** [comment]
No - its an error in my build scripts. I'm just testing the fix.

**Comment by AllanJard** [comment]
I've just released Buttons 2.3.1 which addresses this error. Thanks for letting me know about it.
