### ISSUE TITLE
Cannot read properties of undefined (reading 'defaults')

### ISSUE THREAD

**Issue by barbuslex** [DataTables/Dist-DataTables-Buttons-Bootstrap5#2]
Hi,

I have import datatables with webpack encore like this (following documentation for yarn) :
```js
require('datatables.net-bs5');
const dtLang = require('datatables.net-plugins/i18n/fr-FR.json');
global.dtLang = dtLang
require('datatables.net-buttons-bs5');
require('datatables.net-buttons/js/buttons.print');
```

And i have this error : 
![image](https://user-images.githubusercontent.com/113057/203941439-cbaf09b1-9f0f-4a8b-8ff4-d0228c29fde2.png)

Have you an idea ?

Thanks

**Comment by AllanJard** [comment]
Can you create a mini repo that reproduces the issue so I can dig into this and see what might be going wrong please.

**Comment by barbuslex** [comment]
Fixed with remove all packages and re yarn add modules.
