### ISSUE TITLE
DataTable Buttons are not showing

### ISSUE THREAD

**Issue by rudracomputech** [DataTables/Dist-DataTables-Buttons-Bootstrap5#3]
HI,
I am trying to implement library inside my Laravel vite application but somehow the buttons are not showing and I am not able to figure it out 

package.json

<pre> {
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "dependencies": {
        "@popperjs/core": "^2.11.6",
        "bootstrap": "^5.2.3",
        "chartist": "^0.11.4",
        "chartist-plugin-tooltips": "^0.0.17",
        "datatables.net-bs5": "^1.13.1",
        "datatables.net-buttons": "^2.3.3",
        "datatables.net-buttons-bs5": "^2.3.3",
        "datatables.net-fixedcolumns-bs5": "^4.2.1",
        "datatables.net-fixedheader-bs5": "^3.3.1",
        "datatables.net-responsive-bs5": "^2.4.0",
        "datatables.net-select-bs5": "^1.5.0",
        "jquery": "^3.6.3",
        "notyf": "^3.10.0",
        "nouislider": "^15.2.0",
        "onscreen": "^1.4.0",
        "sass": "^1.47.0",
        "simplebar": "^5.3.4",
        "smooth-scroll": "^16.1.3",
        "sweetalert2": "^11.0.18",
        "vanillajs-datepicker": "^1.2.0",
        "waypoints": "^4.0.1"
    },
    "devDependencies": {
        "@popperjs/core": "^2.11.6",
        "axios": "^1.1.2",
        "bootstrap": "^5.2.3",
        "laravel-vite-plugin": "^0.7.0",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "sass": "^1.56.1",
        "vite": "^3.0.0"
    }
}
</pre>

vite.config.js

<pre>

import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import path from 'path'

export default defineConfig({
    plugins: [
        laravel({
            input: [
               
                'resources/sass/datatables.scss',
                'resources/js/datatables.js',
            ],
            refresh: true,
        }),
    ],
    resolve: {
        alias: {
            '~bootstrap': path.resolve(__dirname, 'node_modules/bootstrap'),
        }
    },
});

</pre>

Datatable.js
<pre>

import  $ from 'jquery';
window.jQuery = window.$ = $

import DataTable from "datatables.net-bs5";

import 'datatables.net-buttons';

import  'datatables.net-buttons-bs5';

import "datatables.net-buttons/js/buttons.colVis.js";
import "datatables.net-buttons/js/buttons.html5.js";
import Buttons from "datatables.net-buttons/js/buttons.print.js";

window.DataTable = DataTable;
$.DataTable = DataTable;
$.fn.DataTable = DataTable;
$.fn.Buttons = Buttons;
DataTable(window, window.$);
Buttons(window, window.$);
</pre>

Blade.php 

<pre>

<script type="module">
    $(document).ready(function() {
  var DataTable =  $('#DataTable').DataTable({
     "dom": "lBftrip",
     "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      });

} );

</script>

</pre>

![bug](https://user-images.githubusercontent.com/8698889/210359391-a7ec3bf8-f3f1-4362-94c8-e0cd9762f2cc.jpg)

Please help!!!

**Comment by AllanJard** [comment]
Hi - could you post support requests in [the DataTables forums](//datatables.net/forums) please? Please include a link to a test case showing the issue or a git repo showing the issue or stackblitz showing it.

**Comment by rudracomputech** [comment]
@AllanJard thankyou for reply here is the stackblitz html generated url  .

https://bootstrap57cjrks-zsob--9000.local-credentialless.webcontainer.io/

https://stackblitz.com/edit/bootstrap-5-7cjrks?file=src/index.html

**Comment by AllanJard** [comment]
Thanks for the links. Unfortunately the first one is giving "Not found" and the Stackblitz one shows an error in the console:

```
success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 12.809s
ERR!: runScript Failed to run `start`. Script is missing.

error Command failed with exit code 1
```

**Comment by rudracomputech** [comment]
Found !!! The datatable.js file was not imported correctly below is correct.

**Datatable.js**
<pre>
import $ from 'jquery';
window.jQuery = window.$ = $;
import DataTable  from 'datatables.net-bs5';
import JSZip from 'jszip';
import 'datatables.net-buttons-bs5';
import 'datatables.net-select-bs5';
import ButtonHtml5 from "datatables.net-buttons/js/buttons.html5.js";
import ButtonPrint from  "datatables.net-buttons/js/buttons.print.js";
import ButtonColvis from  "datatables.net-buttons/js/buttons.colVis.js";
import ButtonPdfHtml5 from  "datatables.net-buttons/js/buttons.html5.js";
import pdfmake from  "pdfmake";
window.DataTable = DataTable;
window.JSZip = JSZip;

JSZip(window, $);
ButtonHtml5(window, $);
ButtonPrint(window, $);
ButtonColvis(window, $);
ButtonPdfHtml5(window, $);
</pre>
